### ISSUE TITLE
Fréttalisti

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#100]
Í ljósi þess að við erum að pimpa vefinn upp (ég veit að þessi síða var aldrei hönnuð, sem slík), þá þurfum við aðeins að hressa upp á fréttayfirlitið.

Myndirnar eru of litlar (thumbnails), og verða hálf klesstar í forminu.  

Ég mæli með að fækka dálkunum niður í tvo (úr þremur) og láta myndina ná amk. 1/2 (jafnvel 2/3) af fyrri dálkinum og textann fljóta meðfram.

Skoðaðu hvernig það kemur út.

**Comment by fizk** [comment]
Ég er sammála því að breyta þessu yfir í tveggja dálka (og ég er búinn að því)

hvað varðar myndina, þá verður þetta einum of með stærri mynd. uppá barndvídd, þá er bara betra að hafa myndina minni
