### ISSUE TITLE
Innskráður notandi í faghóp sér allan faghópalistann.

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#101]
Hann getur líka skoðað hvern meðlim mjög náið (entity spjaldið).  Verður að taka upp á fundi hvort það sé rétt hegðun.

**Comment by fizk** [comment]
Var ekki hugmyndinn að reyna að tengja fólk betur saman innan stjónvísi og ein hugmyndin var að geta sérð profile hjá hvort öðru og svo í framtíðinni senda private message á milli.

en já... þetta er e-ð sem þarf að taka upp á fundi, ákvaða hvað má sjást og hvað ekki... kannskjé mætingarupplýsingarnar eru _einum of_ mikið, þó veit ég ekki...
