### ISSUE TITLE
Stjórnin - Þarf að stíla

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#103]
Það þarf að stíla betur þessa síðu (/stjornin) , og einhvernvegin að útbúa hana þannig að hægt sé að breyta textanum á henni.

**Comment by fizk** [comment]
Mér finnst persónulega ekkert að þessari síðu, en ég gerði samt smá breytingar. Lagaði fornta, setti í þá smá lit og lét Gunnhildi og Stjórnarformanninn vera stærri en stjórnina.

Það sem aðalega þarf, og ástæðan fyrir því að ég er að setja issue'ið yfir á þig er: að það vantar að skrifa almennilegann texa um stjónina, hvenær hún hittist, hvernig hún starfar, hvernig er valið í hana....

og setja þann texta inn... þá mun allt look'a súper flott.

Fyrir Strawberry má svo búa til sér texta per starfsár og geima það í grunninum, þá er hægt að edit'a þann texta... you see @drupalviking ?

![screencapture-localhost-8080-stjornin](https://cloud.githubusercontent.com/assets/386336/6317050/f072ec76-ba93-11e4-8d63-c1a6cd5c1d7f.png)

**Comment by drupalviking** [comment]
Jamms, ég tek þetta á fundinn

**Comment by drupalviking** [comment]
Issue-i lokað og hluti færður yfir í #143
