### ISSUE TITLE
Óinnskráður notandi, sem skráður er á viðburð er illa aðgreindur frá félögum

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#106]
Það er ekki auðvelt að sjá hvort hann sé meðlimur eða ekki, hann Jón

![screen shot 2015-02-22 at 20 57 21](https://cloud.githubusercontent.com/assets/7986212/6320446/79010da2-bad5-11e4-869a-bdcdccf2f178.png)

**Comment by fizk** [comment]
jú, hann er blár... hvað meira viltu?

**Comment by drupalviking** [comment]
Birta þá sér.  Með sér fyrirsögn eða eitthvað, þetta er mjög illskiljanlegt.
