### ISSUE TITLE
Vantar að sækja úr stærri bunka, myndir á forsíðu

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#107]
Núna koma myndir að virðist úr sama viðburðinum, eða amk. ekki fleiri en tveimur.  Það mætti auka pool-ið sem myndirnar eru sóttar úr og gera meira random.

**Comment by drupalviking** [comment]
Jafnvel að random-ize-a í hvert sinn sem síðan refresh-ast.

**Comment by fizk** [comment]
já, ég setti bara 
```sql
order by rand()
```
á þetta...
