### ISSUE TITLE
Of mikill texti í frétt

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#108]
Það þyrfti að brjóta textann aðeins upp, línurnar verða of langar. 

![screen shot 2015-02-23 at 18 02 55](https://cloud.githubusercontent.com/assets/7986212/6333698/26e5cac8-bb87-11e4-8dca-27a2afcbcf77.png)

**Comment by fizk** [comment]
hvar er þetta á síðunni? @drupalviking

**Comment by drupalviking** [comment]
Þegar þú skoðar frétt í detail view.  

Þetta er svolítið tricky.  Ég átti spjall um þetta á Rúv vegna nýja vefsins, og þar var tekin ákvörðun um að hafa textann frekar "narrow", ekki yfir allan skjáinn, vegna þess að það er ekki auðvelt að lesa hann þannig.  

Svolítið usability pælingar, en amk. er textinn of breiður pr. línu, það er ekki gott að lesa hann.

**Comment by fizk** [comment]
það er nott'lega erfitt að lesa þennan texta því hann er ekkert formatt'aður...

en allavegnan

er þetta betra?
![screencapture-localhost-8080-frettir-660](https://cloud.githubusercontent.com/assets/386336/6360220/8d068f5e-bccc-11e4-948a-b9b3569bc3e6.png)

**Comment by drupalviking** [comment]
Mjög gott, ég er mjög sáttur.  Spurning hvort ul listar megi vera með örlítið öðruvísi blæ .... Minna letur, annar fontur  .... veit ekki
