### ISSUE TITLE
Breyta uppsetningu faghópa

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#111]
Í staðinn fyrir að vera með fjóra dálka, og lítinn í texta í þeim öllum, verður þeim fækkað í tvo:  Inngang og meginmál.  Markdown notað í meginmáli.

Einnig þarf að vera hægt að setja inn mynd fyrir hvern faghóp

**Comment by fizk** [comment]
þessi setning

>Einnig þarf að vera hægt að setja inn mynd fyrir hvern faghóp

kallar á nýtt issue

**Comment by fizk** [comment]
buinn
