### ISSUE TITLE
Hover state á Mæti / mæti ekki

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#116]
Það mætti vera hover state á þessum hnöppum .... Transform, rotate 360°og springa svo út á skjáinn .....

Eða kannski bara breyta aðeins um lit.  Ef þeir eru í "unselected state", þá að lyfta þeim í active.... eða stækka aðeins eða eitthvað subtle.

![screen shot 2015-02-24 at 20 53 34](https://cloud.githubusercontent.com/assets/7986212/6358985/770ed0fe-bc67-11e4-977d-53b5a2c6cb6f.png)

**Comment by fizk** [comment]
búinn
