### ISSUE TITLE
Ef notandi er nýr eða ekki í hópi þarf þessi síða að vera "fallegri"

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#117]
/notandi/hopar

![screen shot 2015-02-24 at 20 56 07](https://cloud.githubusercontent.com/assets/7986212/6359008/a5f3fc82-bc67-11e4-93c9-8b832010e438.png)

Þetta er ekki beint fallegt..... Hafa headerinn inni í if setningu og birta einhvern fallegan texta sem bendir á /hopar síðuna.

**Comment by fizk** [comment]
![screen shot 2015-03-10 at 15 30 46](https://cloud.githubusercontent.com/assets/386336/6569200/d9e9fd66-c739-11e4-9ed9-d707e91bc189.png)
![screen shot 2015-03-10 at 15 31 18](https://cloud.githubusercontent.com/assets/386336/6569201/d9edae20-c739-11e4-8819-10757d1cd757.png)
