### ISSUE TITLE
Facebook tenging notanda 

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#118]
Slóðin sem þú gefur upp í enda ferilsins nær út fyrir skjáinn og það er ekki ljóst að hægt sé að scrolla til hægri.  Spurning um að taka pre tagið frá, eða hreinlega minnka fontinn, þannig að öll línan birtist í einu.

Svo má líka bara setja a href og leyfa fólki að smella á helvítið, svona þangað til linkurinn kemur með póstinum (eins og nýr dagur kemur með póstinum)

**Comment by fizk** [comment]
hehe... þetta er sent í pósti núna
