### ISSUE TITLE
Mynd í viðburði / frétt of lítil

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#119]
Myndin er aðeins of lítil, textinn flæðir til vinstri ca. 10%.  Stækka myndina í 100% eða minnka hana í 50%  Ég hallast frekar að því að stækka hana.

![screen shot 2015-02-24 at 21 15 43](https://cloud.githubusercontent.com/assets/7986212/6359360/6d750b50-bc6a-11e4-81f0-1cd0a4ccec24.png)

**Comment by fizk** [comment]
sko við eru að lenda í sama vandamálinu aftur og aftur... með myndir.

málið er þetta...; myndir eru partur af textanum og eru inní texta container'num, þeim eru ekki settar neinar skorður í layout'inu, heldur látnar vera bara eins og mynd í word-skjali.

af því að myndirnar geta verið mismunandi breyðar og og háar, þá skapa það alskonar vezen. Það er ekki ásættanlegt  þegar maður er kominn inní entity page, að myndin sé e-ð crop'uð, hún þarf að vera í réttum hlutföllum.
hún má ekki vera minni en svæðið sem hún á að vera í, þá fer hún að pixlast... ef ég set hana í 100% þá getur hún skalast út í hið óendanlega fyrir stærri upplausnir, ef ég set hana í width:100% og max-width:100% líka, þá getur gerst eins og screenshot'ið sem þú sendir mér... myndin er bara ekki særri en þetta og því hættir hún að vaxa og þá kemst hún Vala Rún fyrir...

ég sé fyrir mér að myndir verði aldrei almennielga fallegar í kerfinu fyrr en við endurhönnum og skoðum aðeins hvernig myndir eru sýndar á entity-pages

**Comment by fizk** [comment]
...en hvað þetta issue varðar... á hvaða síðu er þetta?

dashboard?
fréttalista?
eventlista?
eina stök frétt
einn stakur viðburður?

**Comment by drupalviking** [comment]
Faghópasíðu

**Comment by fizk** [comment]
ég er búinn að taka allar myndir í gegn
