### ISSUE TITLE
Stjórnvísisviðburður þarf að koma inn í feed hjá öllum

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#122]
Þegar viðburður er Stjórnvísisviðburður, þá þarf hann að koma inn í feed-ið hjá öllum, sama feed og faghópafeed notenda (á dashboard-i) notanda.

**Comment by fizk** [comment]
ég skil ekki, hvar koma ekki stjórnvísisviðburðir?
![screen shot 2015-02-27 at 09 13 28](https://cloud.githubusercontent.com/assets/386336/6403013/5580598a-be60-11e4-8731-a61f48d6eb81.png)

**Comment by drupalviking** [comment]
Sorry, þeir koma ekki á gamla vefnum og ég var að koma í veg fyrir að það myndi gerast líka á nýja.
