### ISSUE TITLE
Það vantar verðskrá

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#123]
Talaðu við Gunnhildi og fáðu verðskrá

![screen shot 2015-02-27 at 16 30 46](https://cloud.githubusercontent.com/assets/386336/6407881/74f31928-be9d-11e4-841e-bc06b10f5570.png)

**Comment by drupalviking** [comment]
Það er til verðskrá.

http://stjornvisi.is/adild-og-felagsgjold

Spurning um að hafa bara hlekk á þessa síðu?

**Comment by fizk** [comment]
búúúúinn
