### ISSUE TITLE
Birta hamborgamenu fyrir farsímanotendur

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#136]
Þegar ég er í mobile, þá hef ég ekki aðgang að fídusum eins og hópunum mínum oþh.

![screen shot 2015-03-03 at 05 56 50](https://cloud.githubusercontent.com/assets/7986212/6457206/1582dc10-c16a-11e4-9660-28d31abf3996.png)

**Comment by fizk** [comment]
búinn
