### ISSUE TITLE
"Aðalvalmynd" í mobile

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#137]
Þessir fjórir "týnast" pínu, spurning um að bolda þá og sjá hvað gerist?
![screen shot 2015-03-03 at 05 59 17](https://cloud.githubusercontent.com/assets/7986212/6457216/48f1a9fa-c16a-11e4-8e45-0ba9ec1a16e4.png)

**Comment by fizk** [comment]
**Greinar** eru að fara út, við skulum taka hönnun á þessu...

**Comment by fizk** [comment]
þetta er orðið all öðruvísi
