### ISSUE TITLE
Aðalvalmynd í tablet

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#138]
Þetta er smá klúður hérna.  Hamborgari eða henda í því í fótinn?

![screen shot 2015-03-03 at 06 00 56](https://cloud.githubusercontent.com/assets/7986212/6457234/9694566c-c16a-11e4-8295-c752ed4e4102.png)

**Comment by fizk** [comment]
ok... við erum þá að tala um e-ð svona

![screen shot 2015-03-06 at 10 55 32](https://cloud.githubusercontent.com/assets/386336/6517434/0dec394c-c3ef-11e4-8df0-bfd6cde0aed0.png)
![screen shot 2015-03-06 at 10 56 41](https://cloud.githubusercontent.com/assets/386336/6517435/0df54d66-c3ef-11e4-8412-65e7fdd937a7.png)
![screen shot 2015-03-06 at 10 57 44](https://cloud.githubusercontent.com/assets/386336/6517436/0df5b9ea-c3ef-11e4-9504-ebc8f7f2deb3.png)
