### ISSUE TITLE
Setja fylgiskrár undir í 770px breakpunkti

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#139]
Þetta er of "narrow" eitthvað að hafa þetta svona

![screen shot 2015-03-03 at 06 09 04](https://cloud.githubusercontent.com/assets/7986212/6457292/a1d1eb4c-c16b-11e4-9abe-b1b7f0c2c7cc.png)

**Comment by fizk** [comment]
`aside.layout__aside` brotnar núna undir í `max-width 768px;`
