### ISSUE TITLE
Breyta þarf faghópum þannig að þeir hafi bara inngang og meginmál

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#144]
Hætta með alla þessa dálka sem voru legacy frá Mörtu.

**Comment by drupalviking** [comment]
Búinn að breyta grunninum og formunum þannig að Summary og Body eru komin inn.   Setti svo fyrirsögn fyrir neðan sem bendir faghópunum á að færa á milli.

Fer í að kópa textana  yfir þegar við erum komnir live, og breyti þá display-inu líka þar sem þarf.

**Comment by fizk** [comment]
buid
