### ISSUE TITLE
Notendalistinn er ekki "rétt" uppsettur

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#145]
Notendalistinn þarf að vera í töflu, ekki sem ul listi.  Ástæðan er sú að listanum þarf að vera hægt að raða upp eftir:
+ Nafni
+ Stöðu
+ Fyrirtæki
Og það er ekki hægt í ul lista, fyrir utan að það er cumbersome að lesa þetta.

Ég er búinn að búa til töflu-stöffið, það á eftir að setja sort-hlutann á (geri ráð fyrir að það sé hægt með javascript æfingum) og það á líka eftir að stíla töfluna eða setja amk. á hana pre-defined klasa.

Taflan er svo bara commentuð út, fyrir ofan ul listann í kóðanum.

**Comment by fizk** [comment]
buinn
