### ISSUE TITLE
Hamborgaramenu-inn í iPhone stendur opinn

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#152]
Er búinn að prófa á bæði iPhone6+ og iPhone4, hann virðist ekki loka sér.

**Comment by fizk** [comment]
![screen shot 2015-03-25 at 16 22 36](https://cloud.githubusercontent.com/assets/386336/6818809/d49a86d2-d30a-11e4-963a-e8fdfa770e7c.png)
