### ISSUE TITLE
mynd á viðburði alltof stór

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#156]
wtf
![screencapture-stjornvisi-is-vidburdir-649](https://cloud.githubusercontent.com/assets/386336/6601802/d944eb0e-c86b-11e4-93e3-07b09cc9c87b.png)

http://stjornvisi.is/vidburdir/649

**Comment by drupalviking** [comment]
Sama virðist gerast hér, við frétt:  http://stjornvisi.is/frettir/694

**Comment by fizk** [comment]
ég er búinn að fara yfir stílana... ég er líka búinn að færa myndina í viðburðum yfir í annan column
