### ISSUE TITLE
Say Hello, not Sael(l)

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#169]
Hæ Gunnhildur

Vildi bara segja þér að það fer alltaf í taugarnar á mér að sjá "Sæl(l)", það er eins ópersónulegt og það verður. 
Frekar segja "Góðan daginn" eða "Halló" eða sleppa kveðjunni alveg.

Varð að koma þessu frá mér af því að ég er búinn að hugsa um þetta tvisvar í vikunni, þ.e. búinn að kíkja á tvo pósta frá Stjórnvísi ;)

bestu kveðjur
pétur

**Comment by drupalviking** [comment]
Gunnhildur sjálf ákvað að Sæl(l) væri besta lendingin.
