### ISSUE TITLE
Switch Stjornvisi\Form\NewUserCompany for Stjornvisi\Form\Company

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#22]
Now we have two form that do the same => Stjornvisi\Form\NewUserCompany and Stjornvisi\Form\Company.

We have to use only one. ... this is the plan; use the name Stjornvisi\Form\Company but the code from Stjornvisi\Form\NewUserCompany

**Comment by drupalviking** [comment]
Hvernig stendur þetta ferli?

**Comment by drupalviking** [comment]
Sett í Forgang 1, en tengist #23 að einhverju leiti

**Comment by fizk** [comment]
já, ég loka þessu, issue #23 sér um þetta allt
