### ISSUE TITLE
Create new User

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#23]
Það er ekki búið að útfæra að stofan nýjan notanda

**Comment by drupalviking** [comment]
Og það er heldur ekki búið að útfæra hvernig flæðið er á nýjum notanda, svo fólk sé ekki að stofna alltaf fyrirtæki á sjálft sig.  Þurfum að taka brainstorm á það í vikunni.

**Comment by drupalviking** [comment]
Búinn að setja þetta í forgang, þetta VERÐUR að vera tilbúið í Vanilla.

**Comment by fizk** [comment]
pjúkk... þetta er búið
