### ISSUE TITLE
Stjornvisi\Notify\UserValidate

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#24]
Implement this class

**Comment by drupalviking** [comment]
Inniheldur þessi klasi þá virkni að Gunnhildi verði sendur póstur þegar notandi verður til?  Hún ýtir mjög á það!

**Comment by fizk** [comment]
Nei, þessi klasi mun ekki innihalda þá virkni... hún er annastaðar... það þarf samt aðeins að hanna hana... en ég er búinn að implement'a þennan klasa, svo ég loka kvikindinu bara ;)
