### ISSUE TITLE
Stílíng á forsíðu

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#26]
Það verður að stíla forsíðuna næst.  Hún er það sem allir skoða fyrst þegar þeir koma inn, og vont ef hún breytist ekki.

**Comment by fizk** [comment]
Forsíðan er komin... það má samt alltaf bæta við textum... ég legg það því í þínar hendur @drupalviking að tala við Gunnhildi og fá á hreint hvað textarnir eiga að segja... (ætlaru í alvöru að láta bleslyndann forritarann skrifa textann á forsíðunni)

**Comment by drupalviking** [comment]
Verður tekið fyrir á mánudagsfundinum

**Comment by drupalviking** [comment]
Búinn að laga aðeins textann (stafsetningavillur).  Var tekið fyrir á fundi og óskað eftir textum.  Engir bárust.  Þannig að við setjum þetta bara svona í loftið.
