### ISSUE TITLE
Stíla þarf haus á layout (fyrir óinnskráða)

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#32]
Hausinn er óstílaður með öllu.  Þetta þarf að laga sem fyrst þar sem þetta er eitt af því fyrsta sem þau sjá og munu kvarta yfir.

**Comment by drupalviking** [comment]
Er ekki sami hausinn fyrir innskráða og óinnskráða @fizk, að öðru leyti en á forsíðunni sjálfri, sem er "hauslaus".

**Comment by fizk** [comment]
jú þetta er græjað samanber issue #77 

þannig að ég loka þessu bara
