### ISSUE TITLE
Faghópar birtast ekki

### ISSUE THREAD

**Issue by zormoni** [fizk/Stjornvisi#4]
Faghóparnir sem ég er skráður í birtast hvergi á síðunni

**Comment by drupalviking** [comment]
Þetta er ennþá issue.  Það birtast alltaf allir faghópar, en það er ekkert indication á þá faghópa sem ég er í.  

Spurning hvort við þurfum annað hvort að "Bold-a" þá sem maður er í, eða (sem mér finnst betra) að birta fyrst þá faghópa sem ég er í, og síðan þá faghópa sem mér standa til boða (og ég er ekki í).

**Comment by drupalviking** [comment]
Við þurfum að finna út úr þessu ASAP, verður kvartað yfir þessu á mánudaginn 23. feb., ég er alveg með það á hreinu

**Comment by fizk** [comment]
neinei... þetta er ekkert að þessu... menu'inn vinstamegin sýnir bara þá hópa sem viðkomandi er í

![screen shot 2015-02-22 at 14 37 05](https://cloud.githubusercontent.com/assets/386336/6317301/c63bd088-ba9f-11e4-8e12-d750a0f4cb8d.png)

**Comment by fizk** [comment]
validate'aðu það bara @drupalviking

**Comment by zormoni** [comment]
Já, ég get Validate-að það.  Ég var bara að skoða mig, sem innskráðan.  Og
ég er í öllum helvítis hópunum ;)
