### ISSUE TITLE
Eru of margar fréttir í fréttalista

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#49]
`/frettir/sida/:no` getur verið að það séu of margar fréttir per page?

**Comment by fizk** [comment]
hvað segir þú @drupalviking, nú eru 30 item per page, er það of mikið... verður síðan alltof löööööng?

**Comment by drupalviking** [comment]
Já, 30 item pr. page er alltof mikið.  Færum töluna niður í 15.

Spurning um hvort hægt er að gera paginator-inn þannig að hann sýni 1 2 3 4 5 ... 25 26 27 (eins og margir aðrir page-inator-ar), og miðjusetja hann.

**Comment by fizk** [comment]
ok, ég er búinn að breyta úr 30 niður í 15.

hvað varðar paginatorinn... þá er það ekkert súper mikil forritun að búa til paginator sem gerir [...] á milli svo hann erði ekki of stór.

Það fylgir Paginator view helper með ZF2 en hann gerir ráð fyrir að maður sé að nota þeirra TableDataGateway'ið þeirra... sem við erum svo *sannarlega* ekki að nota... því þarf ég að skrifa mitt eigið...

ég nenni því ekki alveg núna, það er svo marg annað sem þarf að gera, ég loka því þessu issue'i og bú til nýtt fyrir Strawberry sem tæklar þetta

issue #105
