### ISSUE TITLE
Eru aðgengismál í lagi fyrir fréttir

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#55]
formður, stjórn hóps og admin geta græjað fréttir, aðrir ekki

**Comment by drupalviking** [comment]
Óinnskráður getur ekki breytt/eytt/stofnað frétt.  Innskráður getur það ekki heldur

**Comment by fizk** [comment]
hver er þá staðan á þessu... er þetta rétt eða ekki, má loka issue'inu?

**Comment by drupalviking** [comment]
Já, ég er sáttur.
