### ISSUE TITLE
mæti/mæti ekki takkarnir þarf að skoða

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#60]
það verður eiginlega að vera --active class á tökkunum til þess að notandi viti hvort hann hafi áður skráð/afskráð sig á viðburð

**Comment by drupalviking** [comment]
Þetta verður að vera í Vanilla!  Má alls ekki fara í loftið svona.  Þyrfti eiginlega að vera tilbúið fyrir mánudagsfundinn, því þau munu kvarta yfir þessu

**Comment by fizk** [comment]
hvernig er þetta?

sést kannskjé betur á actual síðunni

![screencapture-localhost-8080](https://cloud.githubusercontent.com/assets/386336/6317664/c8e3acfa-bab5-11e4-81ed-8de10be08433.png)

**Comment by drupalviking** [comment]
Verí næs
