### ISSUE TITLE
Myndir vantar 

### ISSUE THREAD

**Issue by zormoni** [fizk/Stjornvisi#7]
Myndir vantar út um allt á Dev servernum.  Væri skynsamlegt að koma þeim yfir þar sem við þurfum að sýna hann fljótlega og ekki gott ef allar myndir eru brotnar.  Geri ráð fyrir að þetta sé bara file-copy vandamál

**Comment by drupalviking** [comment]
Það vantar ennþá myndir á forsíðuna og víðar, spurning um að taka eitt copy frá gamla og yfir?

**Comment by drupalviking** [comment]
Hvernig er staðan á þessu issue-i?

**Comment by fizk** [comment]
ég var búinn að kópera allar myndirnar af gamla yfir á nýja og keyra image-prosessinn á þær... af einhverjum ástæðum komu ekki myndir fyrir svona sirka 10 nýjustu fréttirnar, svo ég bara dúndraði in einhverjum myndum... bara til að það væru myndir

þetta lagast svo þegar gaurinn fer í loftið... en þú ert með nóg til að sýna á mánudaginn
