### ISSUE TITLE
Aðgangsstýring fyrir viðburði

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#71]
hvernig stendur stiginn þar?

**Comment by drupalviking** [comment]
Hvaða aðgangsstýring?  Viltu að það verði farið yfir þær og double-tékkað hvort aðeins þeir sem mega, geta breytt/skoðað/eytt?

**Comment by fizk** [comment]
það er akkúrat það sem ég vil

**Comment by drupalviking** [comment]
Ég er búinn að vera að skoða aðgangsstýringarnar og þær eru að halda.  Get ekkert gert sem óinnskráður, og heldur ekki sem óbreyttur.  Nema skoðað meðlimalista faghóps sem ég er skráður í.  Átti það að vera hægt?
