### ISSUE TITLE
skrá á yfirfullan viðburð

### ISSUE THREAD

**Issue by fizk** [fizk/Stjornvisi#74]
hvað gerist ef notanda tekst að skrá sig á yfirfullan viðburð?

**Comment by drupalviking** [comment]
Það á náttúrulega ekki að vera hægt.  Við þurfum að passa það mjög vel að það gerist ekki.  En annars þarf Gunnhildur að skoða listann og senda tölvupósta held ég.... sé svosem ekki aðra lausn.

Er þetta "feature" hjá okkur, að hægt sé að skrá sig á yfirfullan viðburð?

**Comment by fizk** [comment]
nenniru að prufa að djöflast í þessu og sjá hvað gerist við mismunandi aðstæður?

**Comment by drupalviking** [comment]
Já.

Annars ætti að vera hægt að vera með "biðlista", þannig að ef viðurðurinn er fullur, þá er fólk á biðlista.  Ef einhver afskráir sig, færist viðkomandi upp.

**Comment by drupalviking** [comment]
Það er ekki lengur hægt að skrá sig á fullan viðburð.
