### ISSUE TITLE
Custom Fonts don't load in Firefox, IE and Safari

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#75]
Leturgerðin er vitlaus í textanum Stjórnvísi er stjórnunarfélag.....Vantar skugga í fontinn, fyrir utan að hann er bara kolrangur.

![rangur fontur](https://cloud.githubusercontent.com/assets/7986212/6254954/4f8b4e8a-b7a4-11e4-9545-b249e275d87d.PNG)

**Comment by fizk** [comment]
þetta er stærra vandamál.

fontar virðast ekki load'ast í öllum vöfrum

**Comment by fizk** [comment]
missing woff files.

problem solved
