### ISSUE TITLE
Header er ekki tilbúinn

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#77]
Vantar að stíla betur, leturgerðir eru vitlausar, leitargluggi of lítill og VESKIÐ MITT ER OF ÞRÖNGT FYRIR ALLA FIMMÞÚSUND KALLANA!

**Comment by drupalviking** [comment]
Set þetta í P2, vegna þess að þau munu kvarta yfir þessu á mánudagsfundinum

**Comment by fizk** [comment]
ég sé ekki fyrir mér að leitin komi fyrir mánaðarmót svo ég tók hana bara úr hausnum, þá er nóg pláss.

Seinna meir geri ég issue fyrir Strawberry... *Búa til leit* þá verður þetta tæklað betur... að öðru leiti á hann að vera kominn
