### ISSUE TITLE
Rangur fontur í hópalista

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#79]
Þetta er bara ekki fallegt!  Fonturinn er alltof "þunnur" og bara ekki réttur fontur hér.

![rangur fontur - hopalisti](https://cloud.githubusercontent.com/assets/7986212/6255186/0cff05f0-b7a6-11e4-856d-7ac76809c0aa.PNG)

**Comment by fizk** [comment]
þetta er alveg rétt stærð, litur og fontur... hann bara render'ast mismunandi í Photoshop og Chrome

![screen shot 2015-02-19 at 12 26 18](https://cloud.githubusercontent.com/assets/386336/6260395/35821698-b832-11e4-926c-63e014a3b19f.png)
