### ISSUE TITLE
Rangur fontur í fæti

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#80]
Þetta er engan vegin skv. hönnun, fonturinn alltof "þunnur" og ræfilslegur.  Einnig finnst mér eins og fóturinn sé aðeins "off", þó svo að ég viti ekki alveg hvort ég vilji miðjusetja allan wrapperinn.

**Comment by fizk** [comment]
er þetta betra?

![screen shot 2015-02-19 at 12 23 45](https://cloud.githubusercontent.com/assets/386336/6260350/af516aa6-b831-11e4-80d5-0dbd43d60cd3.png)
![screen shot 2015-02-19 at 12 24 16](https://cloud.githubusercontent.com/assets/386336/6260351/af54d5c4-b831-11e4-8e69-7b390c1c69a8.png)

**Comment by drupalviking** [comment]
Miklu betra
