### ISSUE TITLE
Viðburðadagatal

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#81]
Stækka má aðeins min-height í viku sem hefur enga viðburði, til að dagsetningin sjáist betur.  Einnig mætti hækka opacity-ið á fontinum sem birtir mánaðardaginn aðeins.

Að lokum finnst mér letrið í Viðburðarnafninu sjálfu vera "off", þ.e. ekki fontur sem er í hönnuninn (Arial?)

![vidburdadagatal](https://cloud.githubusercontent.com/assets/7986212/6255297/00a6fe6a-b7a7-11e4-9562-74716475dd18.PNG)

Að lokum finnst mér vanta loftun eða aðra skilgreiningu á milli viðburða, þegar þeir eru fleiri en einn, og það virkar stundum mjög klúðurslega:

![vidburdadagatal - loftun](https://cloud.githubusercontent.com/assets/7986212/6255367/663006d2-b7a7-11e4-8027-0fe265c1fa00.PNG)

Þessi munur á vikum er aðeins "of"

![vidburdadagatal - munur a vikum](https://cloud.githubusercontent.com/assets/7986212/6255421/b0196072-b7a7-11e4-89d7-482c1d701f01.PNG)

**Comment by fizk** [comment]
er þetta betra? herra @drupalviking 

fonturinn á tölunum er samt Open-Sans

![screen shot 2015-02-19 at 11 14 05](https://cloud.githubusercontent.com/assets/386336/6259553/071b65de-b828-11e4-8bba-9df1e10aa9cf.png)

**Comment by drupalviking** [comment]
Miklu betra,
