### ISSUE TITLE
IE9 - Innskráður - Valmynd stendur opin

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#82]
Við innskráningu stendur valmyndin opin og lokast ekki

**Comment by drupalviking** [comment]
Ég get í raun ekki haldið áfram að skoða með IE9 þar sem valmyndin er opin og rennur yfir hnappa og form.

**Comment by fizk** [comment]
ok, ég er setti in html5shiv.js, ég setti það undir IE9 constrictions, ég er búinn að bæta við js skrá sem heitir polyfill og setja hana líka undir IE9 conditions (þar er td. classList polyfill). Ég er búinn að bæta við undir /stylesheets/ie.css (sem er líka undir IE9 conditions) workaround'i fyrir slide in menu'inn

í >=IE9 er ekki notað translate3d(x,y,x) heldur negative left-margin, það sossum kemur út á það sama nema translate3d notar harware acceleration, meðan margin gerir það ekki. Það er sömuleiðis ekkert animation á offscreen menu'inum... en hey, ef þú ætlar að vera með IE9...;)

þannig að @drupalviking endilega... tjékkaðu aftur á IE9

**Comment by drupalviking** [comment]
Búinn að staðfesta að issue-ið er leyst

**Comment by drupalviking** [comment]
Issue-ið er enn til staðar, en nú í Safari á Mac!

**Comment by fizk** [comment]
jebb...

Safari þurfti vendor prefix....

```css
transform: translate3d(0,0,0);
-webkit-transform: translate3d(0,0,0);
```
