### ISSUE TITLE
IE9 - Header tvöfaldur þegar innskráður

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#84]
![header tvofaldur](https://cloud.githubusercontent.com/assets/7986212/6275303/e368e424-b875-11e4-986e-29dd65b8cb27.PNG)

**Comment by drupalviking** [comment]
Er samt í fullscreen

Geri nú ekki ráð fyrir að við þurfum að gera vefinn mjög responsive fyrir IE9 ;)

**Comment by fizk** [comment]
búið
