### ISSUE TITLE
Ekki ljóst hvort ég er skráður á viðburð eða ekki

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#85]
Þetta var miklu betra áður.  Núna hef ég varla hugmynd hvort ég er skráður eða ekki.

![maeti - maeti ekki](https://cloud.githubusercontent.com/assets/7986212/6275443/109212c6-b877-11e4-9621-d041cb368145.PNG)

Svo ýti ég á mæti ekki:

![maeti - maeti ekki 2](https://cloud.githubusercontent.com/assets/7986212/6275474/4f5d9462-b877-11e4-8fee-08b7d0087ace.PNG)

**Comment by drupalviking** [comment]
Ég sé að ég er á listanum, en ég sé ekki í hnöppunum (eins og áður) hvort ég sé búinn að skrá mig eða ekki.

**Comment by drupalviking** [comment]
Svo virðist líka vera sem þetta sé ekki lengur Ajax virkni, heldur full page-reload virkni

**Comment by fizk** [comment]
Það hefur aldrei verið ajax virkni á þessum tökkum... en já, það er satt með að vita ekki hvort ég sé búinn að skrá mig á viðburðinn, og ég er búinn að gera issue um það #60 , svo ræði ég það í issue #90 að það eigi að AJAX væða skráninguna

**Comment by drupalviking** [comment]
Loka þessu issue-i, þar sem commentin eru í öðrum þráðum
