### ISSUE TITLE
Vantar stíla á Admin menu

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#86]
![vantar stila a valmynd](https://cloud.githubusercontent.com/assets/7986212/6275533/b386de26-b877-11e4-8caf-aaa26881f21e.PNG)

**Comment by drupalviking** [comment]
Væri rosalega gott að fá þetta inn fyrir mánudagskvöld, þau munu einblína á þennan "galla"

**Comment by fizk** [comment]
Ok, má þetta ekki vera svona?

![screen shot 2015-02-23 at 07 45 56](https://cloud.githubusercontent.com/assets/386336/6320574/eb9a9968-bb35-11e4-9a32-2d17f661894b.png)
