### ISSUE TITLE
IE9 - Ekki hægt að setja inn mynd í Event, IE9 verður að fá readonly="readonly"

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#87]
![ekki haegt ad setja inn mynd](https://cloud.githubusercontent.com/assets/7986212/6275576/224cfa98-b878-11e4-9dc8-195efd22d028.PNG)

Loaderinn kemur ekki upp

**Comment by drupalviking** [comment]
Þetta er vandamál með IE9 og er ekki í IE10.  Því verður málinu lokað.  Hópastjórar verða að nota > IE10

**Comment by fizk** [comment]
Það verður að setja einhversonar readonly á input'ið ef vafrinn styður ekki XHR2 svo að fólk sé ekki að skrifa e-ð bull í tectaboxið og þá er það ekkert mynd og þá kemur *brotinn myndalinkur* bull á síðuna...

**Comment by drupalviking** [comment]
Ok, þú græjar það í næsta commiti

**Comment by fizk** [comment]
þetta er komið, ég setti bara readonly fyrir alla browser'a því að það á í raun ekkert að fikta í þessu öðruvisi en að smella á þetta til að fá _file-select_ dialog'inn upp eða að draga skrá yfir á þetta til að hlaða henni upp.
