### ISSUE TITLE
Facebook hnappur í vitlausum lit 

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#89]
![screen shot 2015-02-19 at 21 10 24](https://cloud.githubusercontent.com/assets/7986212/6276058/df02011c-b87b-11e4-8a2e-4c912275dd16.png)

Hnappurinn þarf að líkjast því sem notendur eru vanir, því þarf liturinn að matcha Facebook

**Comment by fizk** [comment]
arg... ég á svo erfitt, af estertískum ástæðum, að setja takkann í navy-bláann lit, þar sem ALLIR aðrir litir á síðu eru dempaðir...

hvað segiru @drupalviking um að ég geri meira úr Facebook logo'inu, stækki það og færi til, þannig að það fari ekkert á milli mála að um sé að ræða hið eina sanna Zuckerbörger's Facebook?

**Comment by drupalviking** [comment]
Jú, f-ið stærra, í ramma, eða invertað (á hvítum bakgrunni).

**Comment by fizk** [comment]
ég lét þessa vitleysu eftir þér (híhí) og breytti litnum...

þetta er því non-issue (pun intended)
