### ISSUE TITLE
Mæti / Mæti ekki hnappa vantar á yfirlitssíðu faghóps

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#90]
Þegar ég skoða faghóp ( http://development.stjornvisi.is/hopur/stjornun-vidskiptaferla ) og ég skoða yfirlit viðburða, þarf að vera hægt að segja Mæti / Mæti ekki án þess að fara inn í sjálfan viðburðinn.

![screen shot 2015-02-19 at 21 14 30](https://cloud.githubusercontent.com/assets/7986212/6276132/7b069870-b87c-11e4-92d0-20a0b48eaee7.png)

**Comment by fizk** [comment]
sammála... það er pínu dýrt að vera alltaf að sækja viðburði með tilliti til hvort að notandi sé innskráður og hvort að hann hafi eða hafi ekki skráð sig á viðburð.

í augnablikinu er ekkert AJAX á vefnum, ég veit því ekki alveg hvaðan notandinn var að koma þegar hann skráir sig á viðburð svo ég veit ekki alveg hvert á að senda hann aftur til baka þegar hann er búinn.

@drupalviking lokaðu þessu issue'i og búðu til nýtt um það að það eigi að AJAX-væða mæta/ekki ferlið og settu það í **Strawberry**, við tæklum það svo eftir *lons*

**Comment by drupalviking** [comment]
Ég skal færa Ajax virknina út.  En hitt, að athuga hvort viðkomandi er skráður á viðburð eða ekki .... það verður að vera.  Það er kannski smá dýrt, en á móti kemur er að það er ekkert álag á þessum vef, og þó svo að það þurfi að generate-a síðuna með nokkrum join-um, þá mun það ekki leggja vefinn á hliðina.

**Comment by fizk** [comment]
komið?

![screen shot 2015-02-22 at 17 12 24](https://cloud.githubusercontent.com/assets/386336/6317661/8dd8e206-bab5-11e4-9461-cb5fa039f535.png)

**Comment by drupalviking** [comment]
Glæsilegt.

En biðlisti?  Vorum við eitthvað farnir að hugsa um svoleiðis?  Hugsanlega þurfum við að henda því í Strawberry

**Comment by fizk** [comment]
...já ég veit ekki... 

við skulum allavegana loka þessu issue'i... það er þá hægt að búa til nýtt fyrir biðlista og setja í Strawberry
