### ISSUE TITLE
Útlit á meðlimalista skrítið (Innskráður)

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#91]
Hér virðist vanta Hide fídus eða eitthvað
![screen shot 2015-02-19 at 21 17 28](https://cloud.githubusercontent.com/assets/7986212/6276176/cf963918-b87c-11e4-8765-f669adbc495b.png)

**Comment by drupalviking** [comment]
Einnig er þetta illa útfært, ef listinn er langur verður meðlimalistinn miklu lengri en stjórnarlistinn, og einnig verður allt of mikið hvítt vinstra megin......

Frekar að hafa stjórn fyrir ofan og meðlimi fyrir neðan í þriggja dálka stöffi .....  Og spurning um að bæta við avatar í user-ana, til að geta birt avatars hjá meðlimum.

**Comment by fizk** [comment]
Formenn og stjón er sýnd fyrir alla innskráða, en bara stjón og formenn (og admin) sjá alla meðlimi. Það þarf því að hafa stjón og formenn saman í div og hina í öðrum div (sem er síðan splittað í tvennt).

Hvað varðar rauða hringinn, þá er ég enþá að vinna í því hvernig ég vil hafa edit takkana... þeir þurfa að vera consistant fyrir allt kerfið... ég er bara svona að skoða hvaða CSS trick ég vil gera...

Lokaðu issue'inu ef þú ert ánægður með þetta svar, annas geturu sett það aftur á mig og við getum saman reynda að finna ara lausn sem er betri fyrir augað... annas finnst mér þetta ekkert svo ljótt. sérstaklega ef þú ert bara venjulegur innskráður notandi... því það eru 2-4 einstaklingar sem sjá svona stórann lista, restinn sér bara þessa 2-4 :)

**Comment by drupalviking** [comment]
Nei, ég vil hafa issue-ið áfram opið og við tökum þetta í hangout-i um helgina, og aftur eftir að ég er búinn að fara yfir þessa síðu með Gunnhildi og Halldóri.

**Comment by drupalviking** [comment]
Ég var að prófa notandann hilmar@kosmosogkaos.is  Hann getur séð alla í faghópnum, bæði stjórnendur og aðra.  Hann getur þó engu breytt.

![screen shot 2015-02-21 at 17 40 13](https://cloud.githubusercontent.com/assets/7986212/6315176/905e97c4-b9f1-11e4-9d81-ca481e06e963.png)

**Comment by fizk** [comment]
hmm... þannig að aðgangsstýringin er ekki rétt...

einstaklingur sem er innskráður en er samt ekki formaður eða í stjórn getur samt séð alla...

ok, ég loka þessu issue'i og bú til nýtt sem er villu-issue, þar sem þetta þarf að lagast issue #104
