### ISSUE TITLE
UX á yfirliti inni í faghópi skrítið

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#92]
Ég skil ekki hvaða tilgangi þetta þjónar, þar sem að ég hoppa til á síðunni þegar ég smelli á, og ég geri mér enga grein fyrir hvað í fjandanum er að gerast.

Ég fíla talninguna, en þetta er samt mjög skrítið UX.  Staðsetningin er líka skrítin, fyrir miðri síðu.....

![screen shot 2015-02-19 at 21 19 02](https://cloud.githubusercontent.com/assets/7986212/6276207/17999f16-b87d-11e4-81f5-83b2caa1f7cc.png)

**Comment by drupalviking** [comment]
Ok, ég sé hvað er að ... textinn í lýsingunni er alltof langur:

![screen shot 2015-02-19 at 21 21 30](https://cloud.githubusercontent.com/assets/7986212/6276244/5cfacd32-b87d-11e4-9795-d13a5154ecba.png)

Það verður að minnka þetta eitthvað og bjóða upp á read more eða eitthvað, þetta er óþægilegt að lesa.....

**Comment by fizk** [comment]
Það er mikið á síðunni, og vegna þess að ég vil ekki nota **tabs** til að aggreina conten'tið þá valid ég að setja lítin sub-menu þarna hægra meginn, bara til að ekkert færi fram hjá neinum og það væri súper auðvelt að komast á þann stað sem maður vill fara. 

Ég setti `data-scroll` attribute á hlekkina og þegar ég er orðinn stór húkka ég upp smooth scrolling javascript gaur á þetta svo maður fatti að hvað var að gerast.

En heilt yfir; það er það mikið content á síðunni að hún varð að fá sub-menu... þetta er hann ;)

**Comment by fizk** [comment]
Hvað varðar svona rosalega mikinn texta þarna hægra meginn, þá er ég sammála þér, þetta er aðeins og mikið...

Mér finnst að þegar síðan fer í loftið að við eigum að senda póst á formenn hópa og fá þau til að yfirfara textann, þannig að fyrsta textaboxið fyrir hvern hóp sem hnitmiðara.

Þessi texti er alger undantekning, venjulega eru þeir minni.

Ef þau vilja ekki fari í að laga textana sína, þá setjum við max-width:200px á boxið, og svo **meira** takka sem extendar boxið... en það er bara javascript vinna sem ég nenni ekki alveg núna... það er svo margt annað sem e´g vil frekar vera að laga...

**Comment by drupalviking** [comment]
Issue-i lokað og hluti færður í #144
