### ISSUE TITLE
Ekki birta liðna viðburði sem "næstu viðburði"

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#93]
T.d. á faghópasíðunni:  /hopur

![screen shot 2015-02-19 at 21 44 52](https://cloud.githubusercontent.com/assets/7986212/6276704/a4ccf52e-b880-11e4-915e-b500d7ec862b.png)

**Comment by fizk** [comment]
Sko... ég reyni fyrst að ná í upcomming events og ef það er ekkert á döfinni hjá blessuðum hópnum, þá sæki ég seinust viðburði

````php
$eventLatestStatement = $this->pdo->prepare("
				SELECT E.* FROM `Group_has_Event` GhE
					JOIN `Event` E ON (E.id = GhE.event_id)
				WHERE GhE.group_id = :group_id AND E.`event_date` >= NOW()
				ORDER BY E.event_date ASC
				LIMIT 0, 2");
			//ALL EVENTS
			//	statement to get all events.
			$eventAllStatement = $this->pdo->prepare("
				SELECT E.* FROM `Group_has_Event` GhE
					JOIN `Event` E ON (E.id = GhE.event_id)
				WHERE GhE.group_id = :group_id
				ORDER BY E.event_date DESC
				LIMIT 0, 2");
			//FOR EVERY GROUP
			//	for every group we get events
			array_walk( $groups, function($i) use ($eventLatestStatement, $eventAllStatement){

				//EVENT - PART
				$eventLatestStatement->execute(array('group_id'=>$i->id));
				$i->events = $eventLatestStatement->fetchAll();
				if( count($i->events)==0 ){
					$eventAllStatement->execute(array('group_id'=>$i->id));
					$i->events = $eventAllStatement->fetchAll();
				}
				array_walk( $i->events, function($event){
					$event->event_time = new Time($event->event_date.' '.$event->event_time);
					$event->event_end = ( $event->event_end )
						? new Time($event->event_date.' '.$event->event_end)
						: null ;
					$event->event_date = new  DateTime($event->event_date);
				} );
			} );//...end; for every group
```

ástæðan er sú að ég það er betra að hafa gamalt heldur en ekkert... þá virkar eins og það sé eitthvað að gerast hjá öllum hópunum.


við gætum líka tekið smá fund um þetta, en held og það sem ég ætla að gera er að breyta *næstu viðburðir* yfir í *viðburðir* hvað finnst þér um það?

**Comment by drupalviking** [comment]
Eða vera með ternary á textanum og birta "Næstu viðburðir" ef þeir eru ekki liðnir og "Síðustu viðburðir" ef um eldri viðburði er að ræða, til að rugla nú engan.

Góð pæling, hún bara er ekki augljós.

**Comment by fizk** [comment]
jújú... það má hafa ternary... en eins og þú sérð, þá er ég að gera þetta í Service'num, þannig að þegar ég er kominn niður í view, þá veit ég ekki í raun hvort *statement'in* var keyrð, ég þurfti því að gera 

```
if events[0].date < now()
    print 'viðburðir'
else
    print 'næstu viðburðir'
```

eða e-ð álíka kjánalegt í view'inu, ég nenni því ekki alveg fyrir ekki merkilegri hlut en það...   þú mátt @drupalviking ef þú vilt, loka þessu issue'i og búa til nýtt sem gegnur út á ternary útgáfuna og setja hana á **Strawberry**

**Comment by drupalviking** [comment]
Þú getur auðveldlega bætt við field-i í fyrri select skipunina, sem segir true as active  til að sýna fram á að þú ert þarna með viðburði fram í tímann, og þá það sama í seinni (active as false ):

SELECT E.*, true as 'active' 
FROM `Group_has_Event` GhE
JOIN `Event` E ON (E.id = GhE.event_id)
WHERE GhE.group_id = 7 AND E.`event_date` >= NOW()
ORDER BY E.event_date ASC
LIMIT 0, 2; 

Þá ertu búinn að leysa það vandamál ;-)   

Lausnir, ekki vandamál

**Comment by fizk** [comment]
já, þú ert ekki svo vitlaus... þetta er fín lausn og ég er búinn að útfæra hana
