### ISSUE TITLE
Redundant upplýsingar á faghópasíðu

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#95]
Viðburðir eru birtir tvisvar, þetta er algjörlega redundant:

![screen shot 2015-02-19 at 21 51 10](https://cloud.githubusercontent.com/assets/7986212/6276837/87e22c12-b881-11e4-8043-975987308aa4.png)

**Comment by fizk** [comment]
jú það er satt... sömu upplýsingarnar eru settar tvisvarsinnum fram... en:

* það kostar ekkert að ná í þær aftur, ég þegar búinn að gera service skipunina
* það var e-ð svo tómlegt þarna hægra meginn
* það er gott að geta fengið að ská alla dagskrán í einni skjáfylli

það má sossum alveg taka þetta i burtu, en ég vil smá "fund" um þá áður en ég geri það, ég held nefnilega að það sé beneficial af hafa þetta þarna... hvað segir þú @drupalviking

**Comment by drupalviking** [comment]
Gæti verið gott beneficial já, en um leið þarf þá að skoða og taka ákvaðanir um ýmislegt annað.  Ég mun taka þessa síðu sérstaklega fyrir á fundi á mánudaginn kemur, og raða henni nákvæmlega upp, með öllu því sem tilheyrir.  Gott að hafa svona "kubb" til að bera saman.

**Comment by fizk** [comment]
cool, ég bíð þá frekari fyrirmæla... eftir fund
