### ISSUE TITLE
Avatars hjá meðlimum

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#96]
Ef meðlimir eru með Avatars verður meðlimalistinn miklu flottari.  Setjum það inn í Strawberry

**Comment by fizk** [comment]
avatar mynd kemur ókeypis með ef fólk hefur einusinni skráð sig inn via Facebook

við þurfum svolítið að sjá hversu margir færa sig yfir í Facebook login... það er nefnilega glatað að hafa lista með öllun notendum, profile mynd og allt þegar 99.9% af myndun er **porfile image not found** mynd með silúettu af generic person (sem er svo alltaf kall)

**Comment by fizk** [comment]
Eg se ekki fyrir mer ad folk verdi i miklu maeli ad setja inn myndir ad ser

Myndir koma med Facebook 

Eg vil bida tangad til ad Facebook verdur meira notad... ta getum vid farid ad syna avatar'ana tadan
