### ISSUE TITLE
Útlit fréttayfirlits

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#97]
Í ljósi þess að við erum að pimpa vefinn upp (ég veit að þessi síða var aldrei hönnuð, sem slík), þá þurfum við aðeins að hressa upp á fréttayfirlitið.

Myndirnar eru of litlar (thumbnails), og verða hálf klesstar í forminu.  

Ég mæli með að fækka dálkunum niður í tvo (úr þremur) og láta myndina ná amk. 1/2 (jafnvel 2/3) af fyrri dálkinum og textann fljóta meðfram.

Skoðaðu hvernig það kemur út.

**Comment by drupalviking** [comment]
Eins og þú sérð, þá er myndin voða ræfilsleg hérna:

![screen shot 2015-02-21 at 11 17 31](https://cloud.githubusercontent.com/assets/7986212/6313915/668b73ee-b9bb-11e4-9d2c-dd4244d5e4c4.png)

**Comment by fizk** [comment]
betra?

![screencapture-localhost-8080-frettir- 1](https://cloud.githubusercontent.com/assets/386336/6317417/89e13fb4-baa5-11e4-9494-e8743ade78fc.jpg)

pældu ekki í pagination, ég er búinn að ræða það annarstaðar að þeir fara inní Strawberry

**Comment by drupalviking** [comment]
Mjög gott.  Tvær spurningar samt. 

Hefuru prófað að hafa myndina 100% breidd?  Held að layout-ið þoli það alveg.  

Einnig, page-inator-inn?  Er ekkert hægt að þrengja hann?  S.s. ekki birta allar síðurnar heldur bara range-ið sem þú ert í kringum?

**Comment by fizk** [comment]
ef hún á að vera 100% breið, þá þarf ég að hafa aðra image-style-stærð því að 300px square myndi ekki duga...

við látum þetta duga í bili,

ég var búinn að setja pagination í Strawberry
