### ISSUE TITLE
401 síða ljót

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#98]
401 (Unauthorized) er ljót og þarf að koma fram með betri (en um leið vague skilaboð) um að þú sért einhversstaðar sem þú ættir ekki að vera.

![screen shot 2015-02-21 at 11 53 37](https://cloud.githubusercontent.com/assets/7986212/6313996/7cb4cc42-b9c0-11e4-8652-c16dd1286683.png)

**Comment by fizk** [comment]
betra @drupalviking 

![screencapture-localhost-8080-hopur-breytingastjornun-uppfaera](https://cloud.githubusercontent.com/assets/386336/6317215/d661ceda-ba9b-11e4-85f2-33a0c8e545c2.png)

**Comment by drupalviking** [comment]
Mjög fínt
