### ISSUE TITLE
Draga má starfsárið betur fram

### ISSUE THREAD

**Issue by drupalviking** [fizk/Stjornvisi#99]
Það hverfur svolítið í "fjöldann"

![screen shot 2015-02-21 at 12 02 43](https://cloud.githubusercontent.com/assets/7986212/6314013/a1dcd0b8-b9c1-11e4-957e-54d9b3537306.png)

**Comment by fizk** [comment]
Er þetta betra?

![screen shot 2015-02-22 at 13 57 11](https://cloud.githubusercontent.com/assets/386336/6317176/226578e2-ba9a-11e4-99de-b6cc4c24b97f.png)

**Comment by drupalviking** [comment]
Já
